### ISSUE TITLE
Build wheels for different operating systems.

### ISSUE THREAD

**Issue by yakutovicha** [Probe-Particle/ppafm#106]
Once the release process [is automated](https://github.com/Probe-Particle/ppafm/issues/105), we need to build wheels for different operating systems. This will allow users to not worry about the need for compilation - the CPP code will come pre-compiled already.

**Comment by NikoOinonen** [comment]
There already at least 2 people that have had trouble compiling on Windows (#110), and some difficulties on Linux as well (#135). 

@yakutovicha Could we get some higher priority on this issue? You were setting up things with PyPI before, so I'm assuming you know how to do this. I could also look into it if I just know where to start.

**Comment by NikoOinonen** [comment]
I also ran into this project that promises to automate the builds for all platforms: https://github.com/pypa/cibuildwheel

**Comment by NikoOinonen** [comment]
@yakutovicha  

I read through the PEPs for the `manylinux` tags for the linux wheels:
- `manylinux1`: https://peps.python.org/pep-0513/
- `manylinux2010`: https://peps.python.org/pep-0571/
- `manylinux2014`: https://peps.python.org/pep-0599/
- `manylinux_X_Y`: https://peps.python.org/pep-0600/

It seems that the main rationale for the `manylinux` tags is that different linux distributions have different userspace libraries which limits compatibility for wheels built on different distros. The `manylinux` tags defines a common standard based on the libraries available on different versions of CentOS, with Docker images available.

The standard builds (`python -m build`) don't add these tags, and rather they have to be added manually afterwards. There is a tool called `auditwheel` (https://github.com/pypa/auditwheel) that can be used on a built wheel to check which version of the `manylinux` tag it complies with. In general older versions are desirable, since they are compatible with the most systems.

For the CI build that failed to be uploaded, the version tag that `auditwheel` gives out is `manylinux_2_31_x86_64`, meaning that it's compatible with `glibc` version 2.31 (and newer), which was released in 2020 (https://sourceware.org/glibc/wiki/Glibc%20Timeline). I would target at least as far back as the `manylinux2014` (=`manylinux_2_17`) based on CentOS 7, which is what is running on our local compute cluster.

I think I will try out the [cibuildwheel](https://github.com/pypa/cibuildwheel) that seems to offer CI builds with the different Docker images easily.

**Comment by NikoOinonen** [comment]
Ok, there's now a new `0.2.1` release that comes with the wheels on PyPI. I did a couple of other commits as well, first testing with an alpha release, and fixed one thing in the PyPI upload job.

I tested that the Linux and Windows installation works, but not with Mac, because I don't have one. @yakutovicha Did you have a Mac? If so, could you just quickly try to install from PyPI, just for a sanity check.

**Comment by yakutovicha** [comment]
Thanks, @NikoOinonen, at work, I have Mac with ARM architecture. Here, it downloads `*tar.gz` and compiles it locally (which works, by the way). I need to get back home to try the amd64 one. I will let you know.

**Comment by NikoOinonen** [comment]
There seems to be an option to also build for ARM Macs that can be enabled manually. I can try to enable it.

**Comment by yakutovicha** [comment]
Doesn't seem to work.

```bash
$ pip install ppafm-0.2.1-cp39-cp39-macosx_11_0_arm64.whl
Processing ./ppafm-0.2.1-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: matplotlib in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from ppafm==0.2.1) (3.7.1)
Requirement already satisfied: numpy in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from ppafm==0.2.1) (1.25.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (4.40.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from matplotlib->ppafm==0.2.1) (5.12.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib->ppafm==0.2.1) (3.15.0)
Requirement already satisfied: six>=1.5 in /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->ppafm==0.2.1) (1.16.0)
Installing collected packages: ppafm
Successfully installed ppafm-0.2.1
```
```bash

$ ppafm-generate-ljff
 PACKAGE_PATH =  /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm
 CPP_PATH     =  /Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp
Traceback (most recent call last):
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/bin/ppafm-generate-ljff", line 5, in <module>
    from ppafm.cli.generateLJFF import main
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cli/generateLJFF.py", line 8, in <module>
    import ppafm.fieldFFT as fFFT
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/fieldFFT.py", line 7, in <module>
    from . import io
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/io.py", line 10, in <module>
    from .GridUtils import readNumsUpTo
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/GridUtils.py", line 11, in <module>
    lib = cpp_utils.get_cdll('GU')
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp_utils.py", line 56, in get_cdll
    return ctypes.CDLL(str(module_path)) # Changing to str is required on Windows
  File "/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp/GridUtils_lib.so, 0x0006): tried: '/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp/GridUtils_lib.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp/GridUtils_lib.so' (no such file), '/Users/yaa/miniconda3/envs/ppafm-test-install/lib/python3.9/site-packages/ppafm/cpp/GridUtils_lib.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

The error says that, despite the name, it is still a `x86_64` binary.

**Comment by NikoOinonen** [comment]
I tried it a slightly different way here: https://github.com/Probe-Particle/ppafm/actions/runs/5421634771

They mention in the [documentation](https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2) that at the moment they are cross-compiled on Intel and in the future there should be native ARM CI runners. So if it doesn't work, then maybe let's just skip ARM for now.

**Comment by yakutovicha** [comment]
> I tried it a slightly different way here: https://github.com/Probe-Particle/ppafm/actions/runs/5421634771

Didn't work. I got exactly the same output.

**Comment by yakutovicha** [comment]
On the other hand, on my personal Mac with x86_64 architecture, things worked fine:

```bash
$ pip install ppafm
Collecting ppafm
  Downloading ppafm-0.2.1-cp39-cp39-macosx_10_9_x86_64.whl (599 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.2/599.2 kB 4.6 MB/s eta 0:00:00
...
```
```bash
$ ppafm-generate-ljff
 PACKAGE_PATH =  /Users/yakutovicha/anaconda3/envs/ppafm-test/lib/python3.9/site-packages/ppafm
 CPP_PATH     =  /Users/yakutovicha/anaconda3/envs/ppafm-test/lib/python3.9/site-packages/ppafm/cpp
ERROR!!! Please, specify the input file with the '-i' option

Use this program in the following way:
ppafm-generate-ljff -i <filename>

Supported file fromats are:
    * xyz
```

**Comment by yakutovicha** [comment]
Let's mark the issue as completed. The only "non-working" thing is arm architecture on Mac, which practically still works. There, it downloads the `tar.gz` archive and compiles the code.

**Comment by NikoOinonen** [comment]
Yes, let's close this. I added a small note about the ARM Macs to the wiki: https://github.com/Probe-Particle/ppafm/wiki/Additional-installation-instructions#macos.
