### ISSUE TITLE
readNumsUpTo breaks text file reading

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#113]
It seems that executing `ppafm.GridUtils.readNumsUpTo` causes all subsequent text file reads to fail with an `UnicodeDecodeError`. For a minimal example, try running the following in the graphene example folder after first generating the force fields:
```python
import numpy as np
from ppafm.GridUtils import readNumsUpTo
from ppafm.common import loadParams

readNumsUpTo('FFel_x.xsf', np.array([1, 1, 1], dtype=np.int32), 12)
loadParams('params.ini')
```

This results in a traceback
```
Traceback (most recent call last):
  File "/home/work/git/ppafm/examples/Graphene/test_read.py", line 8, in <module>
    loadParams('params.ini')
  File "/home/work/.local/lib/python3.10/site-packages/ppafm/common.py", line 173, in loadParams
    for line in fin:
  File "/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 465: ordinal not in range(128)
```

If you reverse the order of the two operations, then it works fine. 

The underlying C++ function is messing with the locale, which could be the problem: https://github.com/Probe-Particle/ppafm/blob/74180f913ec13805947bc124f40dd3acd30c0587/ppafm/cpp/GridUtils.cpp#L34

This could also be the cause for the previous issue #89.

**Comment by mondracek** [comment]
Hi,

yes this is very much like my issue #89. I have solved that issue since, 
the problem was in the local environment of our computer grid rather 
than in the code. Namely, the bash variable LANG was not set. Setting it 
to unicode should work, it would be something like `export 
LANG=en_US.UTF-8'. In my case, the line that saved me was

declare -x LANG=$PBS_O_LANG

but that is specific to our grid and the logic goes like this: When a 
job is submitted through the job scheduler, the environment in which the 
job runs does not set the variable LANG by default. I was told it is 
because of the heterogeneity of our grid, establishing any universal 
setup of locale could cause problems on some nodes in some cases. 
However, the scheduler offers a variable called PBS_O_LANG (which, in my 
case, holds the value en_US.UTF-8) and the user can use it do explicitly 
define LANG by the above line when appropriate. Perhaps something 
similar (though probably not exactly identical) may work on your 
computers too.

Martin

**Comment by mondracek** [comment]
Sorry, I did not pay attention to the line with `setclocale` @NikoOinonen mentions as a likely culprit. So while my (closed) issue #89 had similar symptoms, the origin was different. The problem described in #89 was with the locale set by the PBS on my cluster, not in the code. Here, it seems to be the locale set in [ppafm/ppafm/cpp/GridUtils.cpp](https://github.com/Probe-Particle/ppafm/blob/74180f913ec13805947bc124f40dd3acd30c0587/ppafm/cpp/GridUtils.cpp#L34). Okay, but then, why is the call to `setlocale` even needed in GridUtils.cpp?

**Comment by NikoOinonen** [comment]
I tried just commenting out that line with `setlocale` and then it works as expected. And as far as I can tell, that line setting the locale is not actually doing anything, the data is read just the same even without it. @ProkopHapala you added that line several years ago (https://github.com/Probe-Particle/ppafm/commit/b164c0a74672353524b4f7d4e6210a247ee05b08), do you have any recollection for why that should be there?

**Comment by ProkopHapala** [comment]
> I tried just commenting out that line with `setlocale` and then it works as expected. And as far as I can tell, that line setting the locale is not actually doing anything, the data is read just the same even without it. @ProkopHapala you added that line several years ago ([b164c0a](https://github.com/Probe-Particle/ppafm/commit/b164c0a74672353524b4f7d4e6210a247ee05b08)), do you have any recollection for why that should be there?

I don't remember exactly, but I think if was some stupid thing that perhaps on some machines we had czech localizaton and it did not undestant decimal `.` instead of decimal `,` ... but not sure

**Comment by NikoOinonen** [comment]
It actually reads like `1,23454454` in the GUI, with comma as the decimal separator, on my computer and it does not need that locale manipulation to work. So perhaps this is some issue that has been fixed elsewhere in the meanwhile.

I would not add such option before we have some concrete case to investigate any potential problem, so I think I will just delete that line until some actual problem shows up.
