### ISSUE TITLE
Odd sign convention in force calculation

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#149]
When I was implementing the vdw damping functions in the OpenCL code (#130), I was kind of mystified why all of the signs for the forces were reversed in the formulas compared to the C++ implementation. For example, in the case with no damping, in C++ we have https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cpp/Forces.h#L138-L141 and in OpenCL we have https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/ocl/cl/FF.cl#L583-L587 Aside from the different variable names, the only difference is one minus sign on the force vector. However, the result seems to come out the same.

Doing the derivative `F = -dE/dr` on paper, it looks to me like the formula in the OpenCL code is the right one. And it looks to me there is another sign error in the C++ code here https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cpp/ProbeParticle.cpp#L225 where we are calling the force/energy evaluation function with the vector between the probe and the atoms. It should be `rProbe-Ratoms[i]` instead. 

To see this, consider that when we evaluate the force, we are always end up taking the derivative of the distance between the probe and the sample atom, which is something like $\left| a - b \right|$. The derivative of this expression with respect to $a$ is $(a - b) / \left| a - b \right|$. Notice that $a$ is on the front. If we took the derivative with respect to $b$ instead, it would be $(b - a) / \left| a - b \right|$, with the sign reversed and $b$ in the front. In the probe particle model we are always calculating the force on the probe particle, so the derivative should also be with respect to the probe particle position, so it should appear in the front with positive sign.

I'm not sure if this is worth fixing since the result is correct, but I wanted to document it somewhere, because it was causing some headache for me.

@ProkopHapala @ondrejkrejci

**Comment by NikoOinonen** [comment]
In principle it's quite simple, just reverse the sign on the `Ratoms[i]-rProbe` thing, and also reverse the sign on every function that calculates a force. But I'm not too familiar with the overall structure of the C++ code, so I'm not sure if something else could break from changing this.

**Comment by mondracek** [comment]
I've had a look at it now and @NikoOinonen is right about the sign. About the solution as well, I believe. So, we should swap `Ratoms[i] - rProbe` to `Rprobe - Ratoms[i]` in https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cpp/ProbeParticle.cpp#L225
and change sign of all the various atomic force fields implemented as functions in `ppafm/cpp/Force.h`. 
Furthermore, one should probably swap `r, rTip` here https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cpp/ProbeParticle.cpp#L239 too and, correspondingly, change the sign of the restoring force on the deflected probe particle, as implemented here https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/cpp/Forces.h#L87-L91
Where I am not quite sure what to do:
  1. It looks as if the restoring force on the deflected probe particle may be implemented by `forceRSpline` instead of `forceRSpring` in `getPPForce`. I am not sure how the option with the spline works but I suspect the coefficients of the spline function need to be supplied by the user. If so, the proposed change would change the meaning of these coefficients, effectively flipping its sign, wouldn't it? Perhaps we can just flip the sign of the force returned by `forceRSpline` here https://github.com/Probe-Particle/ppafm/blob/2344a7b01000bbf8ce3d2ddbf92abf3b9fe917c9/ppafm/cpp/ProbeParticle.cpp#L182 to keep the meaning of the spline coefficients as they are now. But do we want to keep it? We may instead want to have the sign definition correct for the splines too. As @ondrejkrejci reports  in #74, the example with splines does not currently work anyway, so the backward compatibility might not be an issue. @yakutovicha mentioned that this functionality (do you mean the splines for the tip?) should be deleted so I should perhaps not worry about these, but still, I think we should not break the functionality even more: Either delete it now, or try to repair it and keep working.
  2. I do not know what functions `REQ2PLQ` and `getForceSpringRay` in `Force.h` are supposed to be doing. Should some sign(s) be flipped in them too? I do not see these function being used anywhere. @ProkopHapala, do you know what they were intended for? Perhaps we can use this fix as an opportunity to get rid off them.

**Comment by mondracek** [comment]
I can implement the fix once the issues from my above comment are clarified.

**Comment by ProkopHapala** [comment]
@mondracek 

1.  Yes I would not care about backward compactibility of the spline, it does not work anyway now
2.  In general I have alwasy big chaos in sign-conventions and I always do it by trialand error. I very much appreciate if somebody more organized like you and Niko makes it more consistent, so I relay on your judgement in this issue

`REQ2PLQ` is for converting non-bonding parameters for L-J or Morse potential form format like (R_min, E_min, Charge) into format like ( Pauli_strengh, London_dispersion strenght, Charge). The thing is that repulsive Paili, Attractive Londin, and electrostatics are 3 seperate forcefield. To get total forcefield I sum them up with correspoding coefs, like 

`E_tot = PLQ.x * E_pauli + PLQ.y * E_London +   PLQ.z * E_coulomb`

But I'm not sure if they are used now. I think in the end I perhaps calculate these coefs on the fly, to make the code simpler.

`getForceSpringRay` is a fuction which calculates spring force between a point (position of atoms) and a line (ray from camera). I use it a lot for picking and manipulating molecules in GUI. Maybe I was also using it in the CorrectionLoop where I was moving some atoms. But I think it is not used now. Don't bother with this function.

**Comment by mondracek** [comment]
Another mysterious function in `Forces.h`: `forceSpringRotated`. I would mostly understand what it does, if there were `f_` instead of `dR_` on this line https://github.com/Probe-Particle/ppafm/blob/ca16cfc3814c5bb9d6c40a70103617d02b9d96ed/ppafm/cpp/Forces.h#L106
Is that a bug, @ProkopHapala ? But again, the function does not seem to be used anywhere. 

So I guess this is another function to be ignored. I know, I kind of promised during the discussion today that I was gonna ignore things which I at once do not need and do not understand. I indicated that I have to be reminded about that policy only once in a month or so. Now I already regret the decision the very same day. Never mind, if you tell me to ignore this `forceSpringRotated` function, I will. However, I realize now that this policy of keeping garbage in the code is not for free. I had spent a disproportionate amount of time on this function before I realized what it was and that it could probably be ignored. So it feels like a last-but-one drop to me. With another case like that, sorry, I am going to bring up the topic again and I will start pushing for a strict ***"repair or remove"*** policy. Did @yakutovicha not advocate such a policy a while ago too?

**Comment by ProkopHapala** [comment]
> Another mysterious function in Forces.h: forceSpringRotated. I would mostly understand what it does, if there were f_ instead of dR_ on this line ` rot.dot_to_T( dR_, f ); ` Is that a bug, @ProkopHapala ? But again, the function does not seem to be used anywhere.

Oh, it seems to be the bug. 
If it is not used it examplains why nobody complains.
But I wonder it is not used, we were doing something with rotated tip (but meybe just in OpenCL, mabe this was atempt to compare CPU and GPU). Also I was thinking maybe the tilted osciallation could have used it? (I don't remember)

> So I guess this is another function to be ignored. I know, I kind of promised during the discussion today that I was gonna ignore things which I at once do not need and do not understand.

No, this is not this case. I'm happy you catch it. I do a lot of mistakes, and unless I test it I rarely find it. So good that sombeody as careful as you goes through it and spot it.

what I mean you should ignore is the `/dev` folder, because there is just my unfinished stuff which is not working anyway so I don't want od add you some work.

**Comment by mondracek** [comment]
@ProkopHapala , thanks for the explanation. No problem ignoring the `/dev` folder. So in case I stumble over some function outside `/dev' again, one which is not currently used and which I begin to hate because of its shabby state, can I create some "garbage collector" file(s) inside `/dev` where I will move such functions?

**Comment by mondracek** [comment]
@NikoOinonen 
1. **OCL vesion:** Should I also flip the sign of forces in `ppafm/ocl/cl/FF.cl`? It seems this is going to be necessary because the automatic tests are testing consistency between the C++ and OCL version with respect to the forces
2. **Spring forces**: In the end, I would rather not touch the functions `forceRSpring` (in `ppafm/cpp/Forces.h`) and `getPPforce` (in `ppafm/cpp/ProbeParticle.cpp`) which deal with the spring restoring force. The definition of `drTip` in `getPPforce` is actually correct as it is implemented now. The trick is, the elastic constants `kRadial` and `kSpring` are currently set as negative, see e.g. here https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/HighLevel.py#L109 and here https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/core.py#L109-L110 https://github.com/Probe-Particle/ppafm/blob/8763be1e7e851cb47a1294d49eb04fcd1c14b34b/ppafm/core.py#L113-L114 I may change the definition of `kRadial` and `kSpring` to positive (would have to be done in more places than just those shown above, also some `examples` and `tests` set them directly), but then, additional multiplication by `(-1)` will have to be added to performance critical places in `getPPforce` and `forceRSpring`, without gaining much in terms of clarity of the code.

**Comment by ProkopHapala** [comment]
> @ProkopHapala , thanks for the explanation. No problem ignoring the `/dev` folder. So in case I stumble over some function outside `/dev` again, one which is not currently used and which I begin to hate because of its shabby state, can I create some "garbage collector" file(s) inside `/dev` where I will move such functions?

Generally I think: 
1. if you see something which is obviously wrong and you know how to repair it easily, than just repair it. It is typically faster than anything else.
2. If you find something which looks fishy but you are not sure  how to repair it, and it probably is not used anywhere (so not causing any harm), it is best to write there **comment or docstring** in thet function like `WTF? is this correct? ist this doing what I think it is doing?` or `seems deprecated/ redudant, can we remove it?`
3. If it is something which may be wrong, but it is not obvious how to repair it, or it would require some thinking and more work to repair it, and it may have some effect somewhere, than it is worth discussing as an issue

**Comment by NikoOinonen** [comment]
> OCL vesion: Should I also flip the sign of forces in ppafm/ocl/cl/FF.cl? It seems this is going to be necessary because the automatic tests are testing consistency between the C++ and OCL version with respect to the forces

This should not be necessary. I only noticed the reversed sign in the C++ functions in the first place because it was the opposite from what we had in the OCL version. So if you fix the C++ part, then they should be consistent.

**Comment by mondracek** [comment]
@NikoOinonen , thanks. Now I see that the sign of forces in the `OCL` version was indeed correct. What I needed to change was in fact just a test in `tests/test_vdw.py`, removing the minus sign in front of `x_FF` here https://github.com/Probe-Particle/ppafm/blob/9a75990c881cc4d177677cae245867280c3323b3/tests/test_vdw.py#L48

I think it is ready now. I have created a corresponding PR.
