### ISSUE TITLE
Merge `relaxed_scan_PVE.py` into `relaxed_scan.py`?

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#186]
While doing #185, I noted that the `relaxed_scan_PVE.py` script used in the density overlap model is almost identical to the standard `relaxed_scan.py` except for a couple of additions.

@ProkopHapala Do you think we should merge these two scripts into one? It seems like this could be done quite easily just by adding some argument like `--noLJ` to `relaxed_scan.py`.

**Comment by ProkopHapala** [comment]
Yes, I think it make sense, the reason why `relaxed_scan_PVE.py` is separate is mostly just historical - when I was debugging it I did not want to interfere with the original scripts

**Comment by NikoOinonen** [comment]
Ok, I can do this at some point.

**Comment by mondracek** [comment]
I have increased priority of this proposed merging because I prefer having only one instance of `relax_scan.py` before I try making the KPFM functionality work; see #133.

**Comment by mondracek** [comment]
Not critical issues, but anyway. I copy here my (unfortunately belated) comment from PR #188 . As I indicate at the end of the comment, I can easily create a new Pull Request if you like my ideas, the corresponding branch is already there. Otherwise, if you do not agree with what I propose, you can close this issue again without any further changes to `main`.

First, I agree that the newly introduced --noLJ is the right way to distinguish between the regime which uses the Lennard-Jones potential and the one which reads the Pauli and the separate vdW-only force fields. However, for the sake of user-friendliness, I would prefer to also have the feature that when the user forgets to specify the --noLJ option but his/her working directory lacks the FFLJ_* files while it does contain the FFPpauli_* and FFvdW_* files, the program still defaults to using the separate Pauli and van der Waals force fields.

Second, the present version of the ppafm/examples/pyridineDensOverlap/run.sh script mixes two ways of calling the ppafm scripts: It calls python ${PPAFM_DIR}/generateElFF.py, using the explicitly pre-defined path variable PPAFM_DIR='../../ppafm/cli', but then calls the pip-installed scripts ppafm-relaxed-scan and ppafm-plot-results. I think we should keep python ${PPAFM_DIR}/relaxed_scan.py and python ${PPAFM_DIR}/plot_results here for consistency. This would serve as an example for the user that such way of running the script is also possible. As this older way is currently required for running python ${PPAFM_DIR}/conv_rho.py and python ${PPAFM_DIR}/generateDFTD3.py anyway, this is an opportunity to have an example that does not need the pip installation. Alternatively, we can call the pip-installed ppafm-* scripts for everything, but unless I missed it (because of my outdated code installation), we have yet to add the ppafm-conv-rho and ppafm-generate-dftd3 scripts to our package.

I have a ready alt-relaxed-scan branch that implements the default --noLJ in case of missing FFLJ_* files and modifies the ppafm/examples/pyridineDensOverlap/run.sh, so I can push it if you like the ideas.

**Comment by NikoOinonen** [comment]
>  However, for the sake of user-friendliness, I would prefer to also have the feature that when the user forgets to specify the --noLJ option but his/her working directory lacks the FFLJ_* files while it does contain the FFPpauli_* and FFvdW_* files, the program still defaults to using the separate Pauli and van der Waals force fields.

I think explicit is usually better than implicit. The user could be intending to use LJ and therefore does not use the `--noLJ` option, but happens to have the Pauli and vdW files in the currently directory instead of LJ (maybe running in wrong folder or wrong copy-paste), and then gets the wrong result without noticing. Therefore I think it's better if the program simply tells the user that the appropriate files do not exists in the current folder and exits program, in order to prevent mistakes.

> Second, the present version of the ppafm/examples/pyridineDensOverlap/run.sh script mixes two ways of calling the ppafm scripts: It calls python ${PPAFM_DIR}/generateElFF.py, using the explicitly pre-defined path variable PPAFM_DIR='../../ppafm/cli', but then calls the pip-installed scripts ppafm-relaxed-scan and ppafm-plot-results. I think we should keep python ${PPAFM_DIR}/relaxed_scan.py and python ${PPAFM_DIR}/plot_results here for consistency. This would serve as an example for the user that such way of running the script is also possible. As this older way is currently required for running python ${PPAFM_DIR}/conv_rho.py and python ${PPAFM_DIR}/generateDFTD3.py anyway, this is an opportunity to have an example that does not need the pip installation. Alternatively, we can call the pip-installed ppafm-* scripts for everything, but unless I missed it (because of my outdated code installation), we have yet to add the ppafm-conv-rho and ppafm-generate-dftd3 scripts to our package.

Yes, this sounds good to me. And yes, we haven't added the conv_rho and dftd3 scripts to the installation yet. Not sure if we intend to?

> I have a ready alt-relaxed-scan branch that implements the default --noLJ in case of missing FFLJ_* files and modifies the ppafm/examples/pyridineDensOverlap/run.sh, so I can push it if you like the ideas.

You can make another PR with that branch, and then we can discuss further.

**Comment by ProkopHapala** [comment]
> I think explicit is usually better than implicit. 

I agree

> And yes, we haven't added the conv_rho and dftd3 scripts to the installation yet. Not sure if we intend to?

I think we should add  conv_rho and dftd3 to installation. Or are there some reasons why not?

**Comment by NikoOinonen** [comment]
> I think we should add conv_rho and dftd3 to installation. Or are there some reasons why not?

I don't think there is anything preventing this. It should be pretty simple. Just move the program contents into main functions, and add the scripts to the list in `pyproject.toml`. @mondracek Do you think you could do this in your PR?

**Comment by mondracek** [comment]
Yes, I will try to do it.
