### ISSUE TITLE
Update links to the new paper

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#293]
So we now have the DOI for published version of the paper: https://doi.org/10.1016/j.cpc.2024.109341. We have several places in the repo and the wiki where we are referring to the arXiv version that should be updated to the final version.

I can at least think of the following:
- At the bottom of the main README
- In the script that plots the paper figure: https://github.com/Probe-Particle/ppafm/blob/a036c2e85780032ad1472c15460c757dad252129/examples/paper_figure/run_simulation.py#L4
- In the wiki at https://github.com/Probe-Particle/ppafm/wiki#main-references (which I already updated)

I'm guessing that this paper is also what we want researchers to cite in the future if they use `ppafm` in their research. We could make this clear in the README or elsewhere with a statement like "If you use ppafm in your research, please cite https://doi.org/10.1016/j.cpc.2024.109341".

@ProkopHapala @ondrejkrejci @yakutovicha @aureliojgc @mondracek

**Comment by ProkopHapala** [comment]
Yes, I agree from now on we want users to cite this article

**Comment by ondrejkrejci** [comment]
@mondracek - please could you change the description on the Zenodo (https://zenodo.org/records/10563098), So the url/doi of the paper is mentioned there? Thank you!

**Comment by ondrejkrejci** [comment]
Updating the documentation with the pre-released article:

- [x] Wiki
- [ ] Readme 
- [ ] [ppafm/examples/paper_figure/run_simulation.py](https://github.com/Probe-Particle/ppafm/blob/a036c2e85780032ad1472c15460c757dad252129/examples/paper_figure/run_simulation.py#L4)
- [ ] Zenodo

Udating the documentation, once the issue is available
- [ ] Wiki
- [ ] Readme 
- [ ] [ppafm/examples/paper_figure/run_simulation.py](https://github.com/Probe-Particle/ppafm/blob/a036c2e85780032ad1472c15460c757dad252129/examples/paper_figure/run_simulation.py#L4)
- [ ] Zenodo

**Comment by mondracek** [comment]
@ondrejkrejci Hi, Ondřej.  It seems that the Zenodo records can be edited only by the person who uploaded them and I am not the one who uploaded https://zenodo.org/records/10563098. If it were my record, I should see a "Manage record" button on the top right of the web page, but I do not. I have no idea how to find out who of us uploaded it except that everyone logs into their respective Zenodo account, opens the web page of the record and checks whether he sees the "Manage record" button.

Anyway, as we are in the process of correcting the Zenodo records. The description of the https://zenodo.org/records/10563098 record has a link to another Zenodo record, ``Probe-Particle/PPSTM: real version - 0.1.0`` (https://doi.org/10.5281/zenodo.10669867), the description of which starts with a rather scary note that "The previous release naming is **wrong**" and then continues in this rather grim way. Perhaps this is intentional, so as to warn the reader that the PPSTM implementation is not stable and that it should only be used with the greatest care. If so, at least one typo should be corrected in the description: Change "in compatible" to "incompatible" (remove the superfluous space).

**Comment by ondrejkrejci** [comment]
@mondracek - sorry, being old and have a bad memory (I was guessing it, based on the 1st name ... ). Removed you from the assignees. And good catch about the PPSTM - I have updated the description there.

@NikoOinonen - according to some older issue, it is your repository. Feel free to update it, once the issue is settled.

**Comment by NikoOinonen** [comment]
> @NikoOinonen - according to some older issue, it is your repository. Feel free to update the publication there, once the issue is settled.

Yes, I made that one. I updated it with the DOI. I doubt the DOI is going to change even after they set the issue number, so should be good with this.

**Comment by ondrejkrejci** [comment]
Volume/Issue 305 !
