### ISSUE TITLE
Handling missing lattice vectors

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#52]
There was previously some discussion in #24 on the fact that not all file formats include information on the lattice, which is needed for the force field calculation, and this needs to be handled somehow. 

Some previous suggestions:

From @ondrejkrejci 
> Generally we wanted to offer a possibility to use something like _chemdraw_ for the experimentalist to try 1st approximative simulation. This will of course give you no cell, but then you can specify your cell in the **params.ini** file. I would not restrict using the XYZ format (and others) for having always the cell. (charges are absolutely not necessary if one is using more precise hartree potential from DFT). This change will also have problem with back-compability, I see three possible strategies here:
> 
>     * Leave as is and hope that people knows what they are doing.
> 
>     * During reading of XYZ without cell, we just simply ask, if one has a properly specified cell in the **params.ini** file and write yes.
> 
>     * set:
> 
> 
> ```
> gridA 0.0 0.0 0.0
> gridB 0.0 0.0 0.0
> gridC 0.0 0.0 0.0
> ```
> 
> in https://github.com/Probe-Particle/ProbeParticleModel/blob/main/pyProbeParticle/common.py and https://github.com/Probe-Particle/ProbeParticleModel/blob/main/pyProbeParticle/defaults/params.ini and then have an assert error if after reading both - XYZ (or other geometry file) and **params.ini** the cell has still 0 volume.

From @NikoOinonen 
> I think most of the time if you just draw some molecule, it's going to be in free space and you don't care about periodicity. We could just leave the grid not specified by default, and if it's also not specified in params.ini or the input file, then we can just choose a grid big enough that it encompasses the whole region specified by `scanMin` and `scanMax`. This is actually what I already did in the `AFMulator` in the OpenCL code when the `lvec` parameter is not specified:
> 
> https://github.com/Probe-Particle/ProbeParticleModel/blob/3020d0068b2d3fa8e362aa5d55ef444ac6bcf5fe/pyProbeParticle/ocl/AFMulator.py#L398

Also tagging @yakutovicha @ProkopHapala

**Comment by ondrejkrejci** [comment]
I agree with @NikoOinonen, anyway we should have some kind of warning when one is using this **get_lvec** function,

**Comment by yakutovicha** [comment]
Can someone remind me how this is handled now? Is it only taken from `params.ini`?

**Comment by ondrejkrejci** [comment]
It is taken from `params.ini` in the first part, but then it is  overwritten from files with geometry (_xsf_, _geometry.in_, _POSCAR_, _cube_ ...) if cell is provided there ...

**Comment by yakutovicha** [comment]
> It is taken from `params.ini` in the first part, but then it is overwritten from files with geometry (_xsf_, _geometry.in_, _POSCAR_, _cube_ ...) if cell is provided there ...

Hmm, I see... I thought it would make sense to actually do the opposite: take it from the geometry file and override it if the cell is provided in the `params.ini`.

**Comment by mondracek** [comment]
Okay, I think we have to decide two essentially independent things.
1. Decide what happens when the grid vectors are not specified. What I would definitely *not* do: I would not leave the default hard-wired
 ``gridA: [ 12.798,  -7.3889,  0.00000 ]``
 ``gridB: [ 12.798,   7.3889,  0.00000 ] ``
 ``gridC: [      0,        0,      5.0 ]``
 as it exists now. It does not make sense to me that this particular cell should be somehow universal. Where does it even come from, is it the 6x6 graphene from one of our examples? I would remove this default even if it may cause small troubles with backward compatibility. The users should not rely on these values unless they are working with the specific case of graphene 6x6 (or whatever these values were tuned to). Related to this, ``PBC`` should be ``False`` rather than ``True`` by default. But it should automatically switch to ``True`` if periodicity is defined e.g. through an ``XSF`` file.
 What I do recommend: Set the default (in ``common.py``) as
 ``PBC: False``
 ``gridA: [ 0.0 0.0 0.0 ]``
 ``gridB: [ 0.0 0.0 0.0 ]``
 ``gridC: [ 0.0 0.0 0.0 ]``
 which is to be interpreted as "grid not defined" and if it is not defined later in ``params.ini``, or ``geometry.in``, a ``XSF`` file, ``CUBE`` file etc., set it to encompass the whole scanning region plus some pad as @NikoOinonen suggests and as he does in the ``AFMulater``. Perhaps I would define the "pad" (margin to the scanned area) using  ``r0Probe`` instead of artificially picking one definite value.
2. Another issue is to define what happens when the user specifies the grid (cell) both in ``params.ini`` and in the ``geometry.in`` or ``XSF`` file. I think a warning to the user should definitely be issued in such a case, but I am rather open as for which of the two cells should take precedence. On the one hand, I agree with @yakutovicha that it makes more sense to let the ``params.ini`` override ``geometry.in``, on the other hand, I also understand the issues with backward compatibility @ondrejkrejci mentions. The backward compatibility issues are much more serious than in the point (1) above because we have been copying the ``params.ini`` file with the superfluous cell specification everywhere, relying on the ``geometry.in`` or ``*.xsf`` files to override it, and other users were probably doing the same. So the question is, do we expect that the possibility to redefine the cell as given in ``geometry.in`` though ``params.ini`` is ever going to be useful? If the grid/cell is provided in the ``*.xsf``, it should never get redefined because if it did, the data (potential or charge density) from the ``*.xsf`` file would not make sense any more. However, if the geometry is provided through a ``geometry.in`` or perhaps a ``*.xyz`` file, it is less clear whether the option to redefine the cell should exist or not. What are your opinions?

Anyway, if you agree with my suggestion for (1) and once we decide about (2), I am ready to implement the solution to this issue into the code.

**Comment by NikoOinonen** [comment]
I actually use the probe offset for determining `lvec` in the `AFMulator` (notice `tipR0`):
https://github.com/Probe-Particle/ppafm/blob/3020d0068b2d3fa8e362aa5d55ef444ac6bcf5fe/pyProbeParticle/ocl/AFMulator.py#L398 But, in addition to the probe offset, you also need to take into account that the probe might bend outside the scan region, so you need some padding for that. Also, when convolving the sample potential with the tip density, FFT makes it periodic even when the grid actually isn't, so you need also some padding so that you don't get artefacts from periodic images of the atoms. This is especially true in the z-direction where the scan region is narrow, and the tip density is also more elongated in the z-direction, so you need a little bit of extra pad there (which I set to 3Å by default). 


> What I do recommend: Set the default (in common.py) as
PBC: False
gridA: [ 0.0 0.0 0.0 ]
gridB: [ 0.0 0.0 0.0 ]
gridC: [ 0.0 0.0 0.0 ]

I would maybe do
```python
gridA: None
gridB: None
gridC: None
```
which makes the if-condition a bit simpler in the check (just `if params['gridA'] is None` etc.)

**Comment by ondrejkrejci** [comment]
@mondracek in common.py the vectors are set as follows:
```
    'FFgrid0':     np.array( [ -1.0, -1.0, -1.0 ] ),
    'FFgridA':     np.array( [ -1.0, -1.0, -1.0 ] ),
    'FFgridB':     np.array( [ -1.0, -1.0, -1.0 ] ),
    'FFgridC':     np.array( [ -1.0, -1.0, -1.0 ] ),
```
There is an if for -1.0. that it either read from the files, or the calculations throw and error. I guess that we should change it in [the defaults](https://github.com/Probe-Particle/ppafm/blob/main/ppafm/defaults/params.ini). I agree that we can change it to `None` so it is easily understandable by the readed. The only problem is in GUI, where you have automatically 3 windows for each vector.

**Comment by NikoOinonen** [comment]
@ondrejkrejci Careful, those are different vectors. They are something that I added for compatibility with the `AFMulator` for load parameters for the GUI from `params.ini`.

**Comment by ondrejkrejci** [comment]
There is a possibility of reading the lattice vector from an `*.xyz` file. It is in the comment line, I will add the link, to the ASE code in the future @ondrejkrejci.

**Comment by mondracek** [comment]
Finally, I have ready something that might close this issue. I will submit a pull request in a while, along with some brief comments and explanations what have been done.
As for the default values for lattice vectors, I eventually settled for
```
"gridA": np.array([0.0, 0.0, 0.0]),
"gridB": np.array([0.0, 0.0, 0.0]),
"gridC": np.array([0.0, 0.0, 0.0]),
```
i.e. zero vectors instead of `None`. The reason is, when the lattice vectors are being read from `params.ini`, the parsing function `loadParams` needs to know somehow that it is supposed to read  vectors (triples of floating-point numbers). If I specified the default values as 'None', I would have to find an alternative way to communicate the expected type of the `gridA`, `gridB`, `gridC` parameters to `loadParams` and I do not know how to do it.

**Comment by mondracek** [comment]
Anyway, when solving this issue, I realized that the way our code internally treats the unit-cell parameters (the lattice vectors, the origin, and the grid spacings) is still a mess, even after all the restructuring you have done since last year (but no doubt the cleanup in the structure done so far helped a lot). I will file this complain as a separate issue later and I will try to initiate a discussion about what can done with it there. Also, I will file several more specific issues I have stumbled over when working on this one; these issues are typically rather minor problems in themselves but I believe the common root for them is in fact the messy way of handling the geometric parameters, so I am going to refer to them in the main 'restructuring' issue as examples of why the changes I am gonna propose are needed.
