### ISSUE TITLE
CoPc-IETS example corrupted

### ISSUE THREAD

**Issue by ondrejkrejci** [Probe-Particle/ppafm#71]
https://github.com/Probe-Particle/ppafm/tree/main/examples/CoPc-IETS
error:
```
./run.sh: line 4: 484062 Segmentation fault      python3 ../../relaxed_scan.py --vib 3
```

**Comment by ELpolloGUAPO** [comment]
Hello,
When it would be possible to fix this?
I am learning to use this program and this is exactly the type of system I want to simulate.

**Comment by ondrejkrejci** [comment]
@ProkopHapala, sorry to bother you - just an interesting observation, while checking the current version of PPSTM, I have find out, that the eigenvector procedure is working there fine for [FePc_Au example](https://github.com/Probe-Particle/PPSTM/tree/master/tests/FePc_Au). The overall IETS test is not working, but it calculates the eigenvectors well and store them in an npz file. Thus I am wondering, what can be the problem, that CoPc, which is just free in vaccum has problems and FePc that is flatter and has the extra layer bellow is working fine.

**Comment by ProkopHapala** [comment]
> @ProkopHapala, sorry to bother you - just an interesting observation, while checking the current version of PPSTM, I have find out, that the eigenvector procedure is working there fine for [FePc_Au example](https://github.com/Probe-Particle/PPSTM/tree/master/tests/FePc_Au). The overall IETS test is not working, but it calculates the eigenvectors well and store them in an npz file. Thus I am wondering, what can be the problem, that CoPc, which is just free in vaccum has problems and FePc that is flatter and has the extra layer bellow is working fine.

Aha, interesting, Thanks!. Do you think it is something connected just with the stroring / loading the data (not with the actuall calculation ?)

**Comment by ondrejkrejci** [comment]
@ProkopHapala - I have went to it for a little while and it seems that the problem is somewhere with wrong memory assignment;

The problem is on this line: https://github.com/Probe-Particle/ppafm/blob/a1a7a72ff184a531f687b1f97e947bd75cf6dd78/ppafm/cpp/ProbeParticle.cpp#L627 
And if my _printf_ is really following the mistake in the exact spot, then problematic should be already the second step at that line: `getPPforce( rTip, rPP, f1 );` which sounds strange to me - why it is sometimes working and sometimes not. I am leaving it for now and will work on other things.

**Comment by ondrejkrejci** [comment]
Maybe you can wait for #237 to be merged, so the `ppafm/cli/plot_results.py` is working correctly.

**Comment by ProkopHapala** [comment]
> @ProkopHapala - I have went to it for a little while and it seems that the problem is somewhere with wrong memory assignment;
> https://github.com/Probe-Particle/ppafm/blob/a1a7a72ff184a531f687b1f97e947bd75cf6dd78/ppafm/cpp/ProbeParticle.cpp#L627
> And if my _printf_ is really following the mistake in the exact spot, then problematic should be already the second step at that line: `getPPforce( rTip, rPP, f1 );` which sounds strange to me - why it is sometimes working and sometimes not. I am leaving it for now and will work on other things.

Yes, as I wrote in the email. According tests I did in new [debug_IETS](https://github.com/Probe-Particle/ppafm/tree/debug_IETS) branch the problem is that `gridF` pointer seems invalid at the time wehn we call `stiffnessMatrix()` so `getPPforce()` tries to read from invalid memory address and cause segfault.  I can reproduce the error just by reading `Vec3d gf=gridF[0];` at the begining of `stiffnessMatrix()` as you can as on [this line](https://github.com/Probe-Particle/ppafm/blob/87dde151f73f0e007d41656a2678eb276ad7d916/ppafm/cpp/ProbeParticle.cpp#L635)

I guess the origin of this problem is that Garbage Collector in python deallocate numpy array to which we store the pointer in gridF, because it concludes it is now longer needed. Perhaps we can resolve it if we keep the variable storing the numpy array in proper scope (in Python) - but not sure, need to look on it deeper.
